[package]
name = "stw"
version = "0.0.1"
authors = ["sivese"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano-shaders = "0.19.0"
vulkano-win = "0.19.0"
vulkano = "0.19.0"
vk-sys = "0.5.2"
